name: libadwaita
description: Libadwaita's widgets for Flutter. Following Gnome HIG and available on all platforms.
version: 1.0.0-rc.2
homepage: https://github.com/gtk-flutter/libadwaita

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dbus: ">=0.6.6 <1.0.0"
  flutter:
    sdk: flutter
  gsettings: ">=0.2.1 <1.0.0"

dev_dependencies: 
  very_good_analysis: ^2.4.0

flutter:
